flowchart TB
    maintenant --- jest_27
    maintenant --- react-native_0.68
    maintenant --- testing-library/react-native_10
    maintenant --- react_17
    maintenant --- testing-library/react_12
    testing-library/react-native_10 --> testing-library/react-native_11
    testing-library/react-native_11 --> testing-library/react-native_12
    jest_28 --> testing-library/react-native_12
    jest_27 --> jest_28
    jest_28 --> jest_29
    react-native_0.68 --> react-native_0.69
    react-native_0.69 --> react-native_0.70
    react-native_0.70 --> jest_28
    react-native_0.70 --> react-native_0.71
    react_17 --> react_18
    react_18 --> react-native_0.70
    react_18 --> testing-library/react_13
    testing-library/react_12 --> testing-library/react_13
    testing-library/react_13 --> testing-library/react_14
